### ISSUE TITLE
Path resolution on Windows is incorrect

### ISSUE THREAD

**Issue by xxholly32** [JasKang/vite-plugin-vuedoc#1]
![image](https://user-images.githubusercontent.com/6063358/96551253-91a0a580-12e4-11eb-98e4-f6d4b748ddbc.png)

## reason
1. path solution ([ code line](https://github.com/JasKang/vite-plugin-vuedoc/blob/master/src/resolver.ts#L23)) should add [slash](https://github.com/sindresorhus/slash)
2. markdowntovue ([code line](https://github.com/JasKang/vite-plugin-vuedoc/blob/master/src/markdownToVue.ts#L108)) have the same problem, But I haven't found the cause of the problem yet

---- 

About reason 2：

`markdownToVue.ts`  [code line](https://github.com/JasKang/vite-plugin-vuedoc/blob/master/src/markdownToVue.ts#L108)

console in mac with `vite:rewrite`

```
vite:rewrite     "/Users/xiangxiao/Documents/work/workspace/vite-plugin-vuedoc/playground/src/components/button.docs.md/VUEDEMO_0" --> "/src/components/button.docs.md/VUEDEMO_0" +2ms
```

in windows

```
vite:rewrite     "E:/workspace/vite-plugin-vuedoc/playground/src/components/button.docs.md/VUEDEMO_0" --> "/@modules/E:/workspace/vite-plugin-vuedoc/playground/src/components/button.docs.md/VUEDEMO_0?import" +7ms
```

maybe its vite problem with reg at [codeline](https://github.com/vitejs/vite/blob/master/src/node/server/serverPluginModuleRewrite.ts#L268)

`bareImportRE` just test path in mac

or we should change to relative path

**Comment by JasKang** [comment]
Thank you for your suggestions
i don’t have windows
i m trying to fix this problem, hope it work

**Comment by xxholly32** [comment]
ty for your help
