### ISSUE TITLE
3.0.2版本启动报错

### ISSUE THREAD

**Issue by wjjhhh** [JasKang/vite-plugin-vuedoc#10]
![image](https://user-images.githubusercontent.com/19969184/104538132-433a4300-5656-11eb-9a9c-feb1dc16ef76.png)

**Comment by JasKang** [comment]
window 平台吗

**Comment by wjjhhh** [comment]
> window 平台吗

嗯嗯win10 node12.8.3

**Comment by JasKang** [comment]
fixed: https://github.com/JasKang/vite-plugin-vuedoc/releases/tag/v3.0.4
