### ISSUE TITLE
Broken scoped styles

### ISSUE THREAD

**Issue by neufman** [JasKang/vite-plugin-vuedoc#11]
Some components scoped styles seems broken after plugin inclusion (without options and without use it) :

Before plugin inclusion : 
```css
.d-row[data-v-1fea0806],.d-row[data-v-1fea0806-s] {
...
}
```
After plugin inclusion (hash is added after each selectors) : 
```css
.d-row[data-v-1fea0806][data-v-1fea0806],.d-row[data-v-1fea0806-s][data-v-1fea0806] {
...
}
```

Style in vue file : 
```vue
<style scoped lang="scss">
.d-row, :slotted(.d-row){
...
}
</style>
```

The simple fact of commenting or uncommenting the plugin in the configuration causes the bug or not.

**Comment by JasKang** [comment]
can you provide a demo repo？this will help to locate the problem

**Comment by neufman** [comment]
https://github.com/neufman/vite-plugin-doc-issue-demo.git

To see difference, just comment plugin in vite config.

Seems to be related to the render method.
With template tag, bug doesn't appear.

**Comment by JasKang** [comment]
This problem is caused by the include filter in @vitejs/plugin-vue not taking effect in resolveId and load, causing it to go through the style process twice. So for now, we have to remove the built-in @vitejs/plugin-vue plugin, which causes a Break change

You need to use it like this

```ts
import { defineConfig } from 'vite'
import vitePluginVuedoc, { vueDocFiles } from 'vite-plugin-vuedoc'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vitePluginVuedoc({}),
    vue({
      include: [...vueDocFiles],
    }),
  ],
})

```

**Comment by JasKang** [comment]
> [neufman/vite-plugin-doc-issue-demo.git](https://github.com/neufman/vite-plugin-doc-issue-demo.git)
> 
> To see difference, just comment plugin in vite config.
> 
> Seems to be related to the render method.
> With template tag, bug doesn't appear.

This problem is caused by the include filter in @vitejs/plugin-vue not taking effect in resolveId and load, causing it to go through the style process twice. So for now, we have to remove the built-in @vitejs/plugin-vue plugin, which causes a Break change

You need to use it like this

```ts
import { defineConfig } from 'vite'
import vitePluginVuedoc, { vueDocFiles } from 'vite-plugin-vuedoc'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [
    vitePluginVuedoc({}),
    vue({
      include: [...vueDocFiles],
    }),
  ],
})
```
