### ISSUE TITLE
show/hidden切换问题

### ISSUE THREAD

**Issue by 121595113** [JasKang/vite-plugin-vuedoc#13]
如下代码：
/packages/vite-plugin-vuedoc/src/markdown-it/index.ts
```js
{{ ${id}Height > 0 ? 'hidden' : 'show' }}
```
切换显示隐藏有问题，${id}Height为字符类型，建议修改为：
```js
{{ ${id}Height > '0px' ? 'hidden' : 'show' }}
```

**Comment by JasKang** [comment]
fixed https://github.com/JasKang/vite-plugin-vuedoc/releases/tag/v3.1.3
