### ISSUE TITLE
能否自定义预览代码中的导入模块？

### ISSUE THREAD

**Issue by imengyu** [JasKang/vite-plugin-vuedoc#46]
您好！我正在做一个自定义组件库的文档，使用到了您的预览组件，非常棒，很好用。

但我遇到了一个问题，预览代码中我需要告知用户从我的组件库中导入一个需要使用的配置，并传递给组件，文档中的代码如下所示：

```vue
<template>
    <MyComponent :config="ConstConfig" />
</template>

<script lang="ts" setup>
import { ConstConfig } from 'my-lib'; //导入预设的配置，并传递给组件
</script>
```

现在遇到了一个问题，我希望这个组件可以在文档中实时预览，但实际上代码并不能运行，因为vite找不到我的依赖my-lib。

我把组件库代码和文档放在同一个项目中，方便管理，如果我使用相对路径例如 `import { ConstConfig } from '../../my-lib'; ` 则可以正常导入并显示预览，但这样肯定不行因为看文档的用户如果看到这个相对导入，会觉得很奇怪，并且他如果直接复制代码到他的项目中，就不能导入，如果是库的名称'my-lib', 就没有这个问题。

所以想问问作者 vite-plugin-markdown-preview 有没有什么配置可以增加自定义导入库，比如设置一个配置，可以把导入库映射到本地文件上

**Comment by imengyu** [comment]
解决了，在vite中配置alias就可以了。

```ts
export default defineConfig({
  vite: {
    resolve: {
      alias: {
        'my-lib': '../../lib',
      }
    }
  }
});
```

**Comment by elarbor** [comment]
这个插件不错啊
