### ISSUE TITLE
md files hmr not working in Windows 

### ISSUE THREAD

**Issue by Jenniferyingni** [JasKang/vite-plugin-vuedoc#5]
Hi, JasKang

If I make some changes in  button.docs.md, for instance 
 
```md
  # vite-plugin-vuedoc
```

into

```md
  # vite-plugin-vuedoc-md-hmr-in-windows
```

This request :  /src/components/button.docs.md?type=template

would still remain the same in Windows

However, it works well in Mac

![image](https://user-images.githubusercontent.com/18223971/100086683-b5797d00-2e88-11eb-962e-ed8be221661d.png)

**Comment by JasKang** [comment]
抱歉，之前手里没有 windows ，会尽快加上 测试用例，并在windows 上测试
