### ISSUE TITLE
Could not load path (imported by node_modules\vite-plugin-vuedoc\dist\markdownToVue.js)

### ISSUE THREAD

**Issue by ybom77** [JasKang/vite-plugin-vuedoc#6]
1.yarn add vite-plugin-vuedoc

2.  //vite.config.ts
import vitePluginVuedoc from 'vite-plugin-vuedoc'
const config = {
    base: "./",
    assetsDir: "example/assets",
    plugins: [
        vitePluginVuedoc({
            prism: {
                theme: "okaidia",
            },
        }),
    ]
}
export default config

3.yarn dev 

yarn run v1.22.10
$ vite
[vite] Optimizable dependencies detected:
vite-plugin-vuedoc, vue

[vite] Dep optimization failed with error:
Could not load path (imported by node_modules\vite-plugin-vuedoc\dist\markdownToVue.js): ENOENT: no such file or directory, open 'C:\Users\dengjiali\Documents\emrwriter\emrwriter-vite\path'
[Error: Could not load path (imported by node_modules\vite-plugin-vuedoc\dist\markdownToVue.js): ENOENT: no such file or directory, open 'C:\Users\dengjiali\Documents\emrwriter\emrwriter-vite\path'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\path',
  watchFiles: [
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\vue\\dist\\vue.runtime.esm-bundler.js',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\vite-plugin-vuedoc\\dist\\index.js',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\@vue\\runtime-dom\\dist\\runtime-dom.esm-bundler.js',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\@vue\\shared\\dist\\shared.esm-bundler.js',
    '\x00commonjsHelpers.js',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\@vue\\runtime-core\\dist\\runtime-core.esm-bundler.js',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\@vue\\reactivity\\dist\\reactivity.esm-bundler.js',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\vite-plugin-vuedoc\\dist\\server.js',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\vite-plugin-vuedoc\\dist\\build.js',
    '\x00C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\vite-plugin-vuedoc\\dist\\server.js?commonjs-proxy',
    '\x00C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\vite-plugin-vuedoc\\dist\\build.js?commonjs-proxy',
    '\x00C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\vite-plugin-vuedoc\\dist\\markdownToVue.js?commonjs-proxy',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\vite-plugin-vuedoc\\dist\\markdownToVue.js',
    '\x00C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\debug\\src\\browser.js?commonjs-proxy',
    '\x00C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\slash\\index.js?commonjs-proxy',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\debug\\src\\browser.js',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\slash\\index.js',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\fs-extra\\lib\\index.js',
    '\x00C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\fs-extra\\lib\\index.js?commonjs-proxy',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\vite-plugin-vuedoc\\dist\\remark\\index.js',
    '\x00C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\vite-plugin-vuedoc\\dist\\remark\\index.js?commonjs-proxy',
    '\x00C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\debug\\src\\common.js?commonjs-proxy',
    'C:\\Users\\dengjiali\\Documents\\emrwriter\\emrwriter-vite\\node_modules\\debug\\src\\common.js',
    'path',
    '\x00path?commonjs-proxy'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

how to fix this

**Comment by ybom77** [comment]
。

**Comment by JasKang** [comment]
> 。

Is it resolved?

**Comment by ybom77** [comment]
> > 。
> 
> Is it resolved?

that's my problem

**Comment by Month7** [comment]
> > > 。
> > 
> > 
> > Is it resolved?
> 
> that's my problem

I have the same problem, how did you solve it
