### ISSUE TITLE
与vite2.0 不兼容

### ISSUE THREAD

**Issue by shlroland** [JasKang/vite-plugin-vuedoc#8]
vite2.0修改了部分api 是否有更新计划

**Comment by JasKang** [comment]
今明两天内会更新

**Comment by JasKang** [comment]
> vite2.0修改了部分api 是否有更新计划

今明两天内会更新

**Comment by JasKang** [comment]
https://github.com/JasKang/vite-plugin-vuedoc/releases/tag/3.0.0-0
